USE CiudadInteligenteMER;
GO
INSERT INTO Geo.Pais
    (Nombre, CodigoISO3)
VALUES
    ('Afganistán', 'AFG'),
    ('Albania', 'ALB'),
    ('Alemania', 'DEU'),
    ('Andorra', 'AND'),
    ('Angola', 'AGO'),
    ('Antigua y Barbuda', 'ATG'),
    ('Arabia Saudita', 'SAU'),
    ('Argelia', 'DZA'),
    ('Argentina', 'ARG'),
    ('Armenia', 'ARM'),
    ('Australia', 'AUS'),
    ('Austria', 'AUT'),
    ('Azerbaiyán', 'AZE'),
    ('Bahamas', 'BHS'),
    ('Bangladés', 'BGD'),
    ('Barbados', 'BRB'),
    ('Baréin', 'BHR'),
    ('Bélgica', 'BEL'),
    ('Belice', 'BLZ'),
    ('Benín', 'BEN'),
    ('Bielorrusia', 'BLR'),
    ('Birmania', 'MMR'),
    ('Bolivia', 'BOL'),
    ('Bosnia y Herzegovina', 'BIH'),
    ('Botsuana', 'BWA'),
    ('Brasil', 'BRA'),
    ('Brunéi', 'BRN'),
    ('Bulgaria', 'BGR'),
    ('Burkina Faso', 'BFA'),
    ('Burundi', 'BDI'),
    ('Bután', 'BTN'),
    ('Cabo Verde', 'CPV'),
    ('Camboya', 'KHM'),
    ('Camerún', 'CMR'),
    ('Canadá', 'CAN'),
    ('Catar', 'QAT'),
    ('Chad', 'TCD'),
    ('Chile', 'CHL'),
    ('China', 'CHN'),
    ('Chipre', 'CYP'),
    ('Colombia', 'COL'),
    ('Comoras', 'COM'),
    ('Corea del Norte', 'PRK'),
    ('Corea del Sur', 'KOR'),
    ('Costa de Marfil', 'CIV'),
    ('Costa Rica', 'CRI'),
    ('Croacia', 'HRV'),
    ('Cuba', 'CUB'),
    ('Dinamarca', 'DNK'),
    ('Dominica', 'DMA'),
    ('Ecuador', 'ECU'),
    ('Egipto', 'EGY'),
    ('El Salvador', 'SLV'),
    ('Emiratos Árabes Unidos', 'ARE'),
    ('Eritrea', 'ERI'),
    ('Eslovaquia', 'SVK'),
    ('Eslovenia', 'SVN'),
    ('España', 'ESP'),
    ('Estados Unidos', 'USA'),
    ('Estonia', 'EST'),
    ('Esuatini', 'SWZ'),
    ('Etiopía', 'ETH'),
    ('Filipinas', 'PHL'),
    ('Finlandia', 'FIN'),
    ('Fiyi', 'FJI'),
    ('Francia', 'FRA'),
    ('Gabón', 'GAB'),
    ('Gambia', 'GMB'),
    ('Georgia', 'GEO'),
    ('Ghana', 'GHA'),
    ('Granada', 'GRD'),
    ('Grecia', 'GRC'),
    ('Guatemala', 'GTM'),
    ('Guinea', 'GIN'),
    ('Guinea-Bisáu', 'GNB'),
    ('Guinea Ecuatorial', 'GNQ'),
    ('Guyana', 'GUY'),
    ('Haití', 'HTI'),
    ('Honduras', 'HND'),
    ('Hungría', 'HUN'),
    ('India', 'IND'),
    ('Indonesia', 'IDN'),
    ('Irak', 'IRQ'),
    ('Irán', 'IRN'),
    ('Irlanda', 'IRL'),
    ('Islandia', 'ISL'),
    ('Islas Marshall', 'MHL'),
    ('Islas Salomón', 'SLB'),
    ('Israel', 'ISR'),
    ('Italia', 'ITA'),
    ('Jamaica', 'JAM'),
    ('Japón', 'JPN'),
    ('Jordania', 'JOR'),
    ('Kazajistán', 'KAZ'),
    ('Kenia', 'KEN'),
    ('Kirguistán', 'KGZ'),
    ('Kiribati', 'KIR'),
    ('Kuwait', 'KWT'),
    ('Laos', 'LAO'),
    ('Lesoto', 'LSO'),
    ('Letonia', 'LVA'),
    ('Líbano', 'LBN'),
    ('Liberia', 'LBR'),
    ('Libia', 'LBY'),
    ('Liechtenstein', 'LIE'),
    ('Lituania', 'LTU'),
    ('Luxemburgo', 'LUX'),
    ('Macedonia del Norte', 'MKD'),
    ('Madagascar', 'MDG'),
    ('Malasia', 'MYS'),
    ('Malaui', 'MWI'),
    ('Maldivas', 'MDV'),
    ('Malí', 'MLI'),
    ('Malta', 'MLT'),
    ('Marruecos', 'MAR'),
    ('Mauricio', 'MUS'),
    ('Mauritania', 'MRT'),
    ('México', 'MEX'),
    ('Micronesia', 'FSM'),
    ('Moldavia', 'MDA'),
    ('Mónaco', 'MCO'),
    ('Mongolia', 'MNG'),
    ('Montenegro', 'MNE'),
    ('Mozambique', 'MOZ'),
    ('Namibia', 'NAM'),
    ('Nauru', 'NRU'),
    ('Nepal', 'NPL'),
    ('Nicaragua', 'NIC'),
    ('Níger', 'NER'),
    ('Nigeria', 'NGA'),
    ('Noruega', 'NOR'),
    ('Nueva Zelanda', 'NZL'),
    ('Omán', 'OMN'),
    ('Países Bajos', 'NLD'),
    ('Pakistán', 'PAK'),
    ('Palaos', 'PLW'),
    ('Panamá', 'PAN'),
    ('Papúa Nueva Guinea', 'PNG'),
    ('Paraguay', 'PRY'),
    ('Perú', 'PER'),
    ('Polonia', 'POL'),
    ('Portugal', 'PRT'),
    ('Reino Unido', 'GBR'),
    ('República Centroafricana', 'CAF'),
    ('República Checa', 'CZE'),
    ('República del Congo', 'COG'),
    ('República Democrática del Congo', 'COD'),
    ('República Dominicana', 'DOM'),
    ('Ruanda', 'RWA'),
    ('Rumanía', 'ROU'),
    ('Rusia', 'RUS'),
    ('Samoa', 'WSM'),
    ('San Cristóbal y Nieves', 'KNA'),
    ('San Marino', 'SMR'),
    ('San Vicente y las Granadinas', 'VCT'),
    ('Santa Lucía', 'LCA'),
    ('Santo Tomé y Príncipe', 'STP'),
    ('Senegal', 'SEN'),
    ('Serbia', 'SRB'),
    ('Seychelles', 'SYC'),
    ('Sierra Leona', 'SLE'),
    ('Singapur', 'SGP'),
    ('Siria', 'SYR'),
    ('Somalia', 'SOM'),
    ('Sri Lanka', 'LKA'),
    ('Sudáfrica', 'ZAF'),
    ('Sudán', 'SDN'),
    ('Sudán del Sur', 'SSD'),
    ('Suecia', 'SWE'),
    ('Suiza', 'CHE'),
    ('Surinam', 'SUR'),
    ('Tailandia', 'THA'),
    ('Tanzania', 'TZA'),
    ('Tayikistán', 'TJK'),
    ('Timor Oriental', 'TLS'),
    ('Togo', 'TGO'),
    ('Tonga', 'TON'),
    ('Trinidad y Tobago', 'TTO'),
    ('Túnez', 'TUN'),
    ('Turkmenistán', 'TKM'),
    ('Turquía', 'TUR'),
    ('Tuvalu', 'TUV'),
    ('Ucrania', 'UKR'),
    ('Uganda', 'UGA'),
    ('Uruguay', 'URY'),
    ('Uzbekistán', 'UZB'),
    ('Vanuatu', 'VUT'),
    ('Vaticano', 'VAT'),
    ('Venezuela', 'VEN'),
    ('Vietnam', 'VNM'),
    ('Yemen', 'YEM'),
    ('Yibuti', 'DJI'),
    ('Zambia', 'ZMB'),
    ('Zimbabue', 'ZWE');
GO

INSERT INTO Geo.Departamento
    (Nombre, IdPais)
VALUES
    ('Amazonas', 41),
    ('Antioquia', 41),
    ('Arauca', 41),
    ('Atlántico', 41),
    ('Bolívar', 41),
    ('Boyacá', 41),
    ('Caldas', 41),
    ('Caquetá', 41),
    ('Casanare', 41),
    ('Cauca', 41),
    ('Cesar', 41),
    ('Chocó', 41),
    ('Córdoba', 41),
    ('Cundinamarca', 41),
    ('Guainía', 41),
    ('Guaviare', 41),
    ('Huila', 41),
    ('La Guajira', 41),
    ('Magdalena', 41),
    ('Meta', 41),
    ('Nariño', 41),
    ('Norte de Santander', 41),
    ('Putumayo', 41),
    ('Quindío', 41),
    ('Risaralda', 41),
    ('San Andrés y Providencia', 41),
    ('Santander', 41),
    ('Sucre', 41),
    ('Tolima', 41),
    ('Valle del Cauca', 41),
    ('Vaupés', 41),
    ('Vichada', 41);
GO

USE CiudadInteligenteMER;
GO
INSERT INTO Geo.Municipio
    (Nombre, IdDepartamento)
VALUES
    ('Agua de Dios', 14),
    ('Albán', 14),
    ('Anapoima', 14),
    ('Anolaima', 14),
    ('Apulo', 14),
    ('Arbeláez', 14),
    ('Beltrán', 14),
    ('Bituima', 14),
    ('Bojacá', 14),
    ('Cabrera', 14),
    ('Cachipay', 14),
    ('Cajicá', 14),
    ('Caparrapí', 14),
    ('Caqueza', 14),
    ('Carmen de Carupa', 14),
    ('Chaguaní', 14),
    ('Chía', 14),
    ('Chipaque', 14),
    ('Choachí', 14),
    ('Chocontá', 14),
    ('Cogua', 14),
    ('Cota', 14),
    ('Cucunubá', 14),
    ('El Colegio', 14),
    ('El Peñón', 14),
    ('El Rosal', 14),
    ('Facatativá', 14),
    ('Fomeque', 14),
    ('Fosca', 14),
    ('Funza', 14),
    ('Fúquene', 14),
    ('Fusagasugá', 14),
    ('Gachalá', 14),
    ('Gachancipá', 14),
    ('Gachetá', 14),
    ('Gama', 14),
    ('Girardot', 14),
    ('Granada', 14),
    ('Guachetá', 14),
    ('Guaduas', 14),
    ('Guasca', 14),
    ('Guataquí', 14),
    ('Guatavita', 14),
    ('Guayabal de Síquima', 14),
    ('Guayabetal', 14),
    ('Gutiérrez', 14),
    ('Jerusalén', 14),
    ('Junín', 14),
    ('La Calera', 14),
    ('La Mesa', 14),
    ('La Palma', 14),
    ('La Peña', 14),
    ('La Vega', 14),
    ('Lenguazaque', 14),
    ('Machetá', 14),
    ('Madrid', 14),
    ('Manta', 14),
    ('Medina', 14),
    ('Mosquera', 14),
    ('Nariño', 14),
    ('Nemocón', 14),
    ('Nilo', 14),
    ('Nimaima', 14),
    ('Nocaima', 14),
    ('Venecia', 14),
    ('Pacho', 14),
    ('Paime', 14),
    ('Pandi', 14),
    ('Paratebueno', 14),
    ('Pasca', 14),
    ('Puerto Salgar', 14),
    ('Pulí', 14),
    ('Quebradanegra', 14),
    ('Quetame', 14),
    ('Quipile', 14),
    ('Ricaurte', 14),
    ('San Antonio del Tequendama', 14),
    ('San Bernardo', 14),
    ('San Cayetano', 14),
    ('San Francisco', 14),
    ('San Juan de Rioseco', 14),
    ('Sasaima', 14),
    ('Sesquilé', 14),
    ('Sibaté', 14),
    ('Silvania', 14),
    ('Simijaca', 14),
    ('Soacha', 14),
    ('Sopó', 14),
    ('Subachoque', 14),
    ('Suesca', 14),
    ('Supatá', 14),
    ('Susa', 14),
    ('Sutatausa', 14),
    ('Tabio', 14),
    ('Tausa', 14),
    ('Tena', 14),
    ('Tenjo', 14),
    ('Tibacuy', 14),
    ('Tibirita', 14),
    ('Tocaima', 14),
    ('Tocancipá', 14),
    ('Topaipí', 14),
    ('Ubalá', 14),
    ('Ubaque', 14),
    ('Ubaté', 14),
    ('Une', 14),
    ('Útica', 14),
    ('Vergara', 14),
    ('Vianí', 14),
    ('Villagómez', 14),
    ('Villapinzón', 14),
    ('Villeta', 14),
    ('Viotá', 14),
    ('Yacopí', 14),
    ('Zipacón', 14),
    ('Zipaquirá', 14);

INSERT INTO Geo.Barrio
    (Nombre, IdMunicipio)
VALUES
    ('La Balsa', 17),
    ('La Lorena', 17),
    ('La Libertad', 17),
    ('La Estancia', 17),
    ('La Valvanera', 17),
    ('La Campiña', 17),
    ('La Pradera', 17),
    ('La Riviera', 17),
    ('La Caro', 17),
    ('La Macarena', 17),
    ('La Ponderosa', 17),
    ('La Montaña', 17),
    ('La Primavera', 17),
    ('La Sabana', 17),
    ('La Fontana', 17),
    ('La Esmeralda', 17),
    ('La Floresta', 17),
    ('La Villa', 17),
    ('La Esperanza', 17),
    ('La Candelaria', 17),
    ('La Hacienda', 17),
    ('La Arboleda', 17),
    ('La Aurora', 17),
    ('La Alameda', 17),
    ('La Castellana', 17),
    ('La Toscana', 17),
    ('La Reserva', 17),
    ('La Ciudadela', 17),
    ('La Vereda Bojacá', 17),
    ('La Vereda Fonquetá', 17),
    ('La Vereda Fagua', 17),
    ('La Vereda Cerca de Piedra', 17),
    ('La Vereda Yerbabuena', 17),
    ('La Vereda Tiquiza', 17),
    ('La Vereda Samaria', 17),
    ('La Vereda La Balsa', 17),
    ('La Vereda La Caro', 17),
    ('La Vereda La Valvanera', 17),
    ('La Vereda La Montaña', 17),
    ('La Vereda La Pradera', 17),
    ('La Vereda La Campiña', 17),
    ('La Vereda La Macarena', 17),
    ('La Vereda La Ponderosa', 17),
    ('La Vereda La Primavera', 17),
    ('La Vereda La Sabana', 17),
    ('La Vereda La Fontana', 17),
    ('La Vereda La Esmeralda', 17),
    ('La Vereda La Floresta', 17),
    ('La Vereda La Villa', 17),
    ('La Vereda La Esperanza', 17);

INSERT INTO Geo.TipoZona
    (Nombre)
VALUES
    ('Urbano'),
    ('Rural'),
    ('Industrial'),
    ('Comercial'),
    ('Residencial'),
    ('Mixto'),
    ('Protección Ambiental');

SELECT COUNT(*) AS TotalPaises
FROM Geo.Pais;

SELECT COUNT(*) AS TotalDepartamentos
FROM Geo.Departamento;

SELECT COUNT(*) AS TotalMunicipios
FROM Geo.Municipio;

SELECT COUNT(*) AS TotalBarrios
FROM Geo.Barrio;

SELECT COUNT(*) AS TotalTipoZonas
FROM Geo.TipoZona;